# Generated by Django 5.0.6 on 2024-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_addstaff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstaff",
            name="number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="addstaff",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
