# Generated by Django 5.0.6 on 2024-06-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0003_alter_addstaff_number_alter_addstaff_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstaff",
            name="type",
            field=models.CharField(max_length=70),
        ),
    ]
