# Generated by Django 5.0.6 on 2024-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="addstaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=150)),
                ("username", models.CharField(max_length=30)),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("number", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=20)),
            ],
        ),
    ]
