# Generated by Django 5.0.6 on 2024-06-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_addstaff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstaff",
            name="email",
            field=models.CharField(max_length=200),
        ),
    ]
