# Generated by Django 5.0.6 on 2024-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0004_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="addstaff",
            name="awards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="addstaff",
            name="city",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="country",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="experience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="gender",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="graduation_year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="hobbies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="addstaff",
            name="languages",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="medical_license",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="medical_school",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addstaff",
            name="publications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="addstaff",
            name="specialization",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
