# Generated by Django 5.0.6 on 2024-06-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0005_addstaff_awards_addstaff_city_addstaff_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduled",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduled",
            name="time_slot",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
