# Generated by Django 5.0.6 on 2024-06-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0007_scheduled_allergies_scheduled_blood_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduled",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="scheduled",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="scheduled",
            name="current_medication",
        ),
        migrations.RemoveField(
            model_name="scheduled",
            name="gender",
        ),
    ]
