# Generated by Django 5.0.6 on 2024-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0011_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduled",
            name="time_slot",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="slot",
            name="time_slot",
            field=models.CharField(max_length=20),
        ),
    ]
