# Generated by Django 5.0.6 on 2024-06-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0013_medicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("LIQUID", "Liquid"),
                    ("SOLID", "Solid"),
                    ("TUBE", "Tube"),
                    ("POWDER", "Powder"),
                ],
                default=0,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
