# Generated by Django 5.0.6 on 2024-06-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0015_medication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="patient_email",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="medication",
            name="doctor",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app2.addstaff",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medication",
            name="patient",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="app2.patientt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medication",
            name="time_schedule",
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
