# Generated by Django 5.0.6 on 2024-06-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0016_remove_medication_doctor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduled",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
