# Generated by Django 5.0.6 on 2024-06-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0017_scheduled_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app2.scheduled",
            ),
        ),
    ]
