# Generated by Django 5.0.6 on 2024-06-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0018_medication_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="appointment",
        ),
    ]
