# Generated by Django 5.0.6 on 2024-06-26 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0019_remove_medication_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="schedule_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
