# Generated by Django 5.0.6 on 2024-06-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0020_medication_schedule_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_room",
                    models.CharField(
                        choices=[
                            ("AC", "AC Room"),
                            ("Non-AC", "Non-AC Room"),
                            ("General", "General Room"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
