# Generated by Django 5.0.6 on 2024-06-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0021_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app2.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.FloatField(),
        ),
    ]
