# Generated by Django 5.0.6 on 2024-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0022_medication_room_alter_room_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="room_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="room_type",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
