# Generated by Django 5.0.6 on 2024-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0023_medication_room_price_medication_room_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="room_type",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
